name: github-action-destroy

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "main" ]
env:
  BUCKET: hafsa-bucket-1
  TFSTATE_FILE: hafsa.tfstate
  DB_TABLE: hafsa-table-1

jobs:
  tf-destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Test_Module

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: tf-init
        id: init
        run: 
          terraform init -reconfigure
          -backend-config="bucket=$BUCKET"
          -backend-config="key=$TFSTATE_FILE"
          -backend-config="dynamodb_table=$DB_TABLE"

      - name: tf-destroy-plan
        id: plan
        run: terraform plan -destroy

      - name: tf-destroy-apply
        id: destroy
        run: terraform destroy -auto-approve